---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: Se necessario, è possibile aggiungere altri account per migliorare le prestazioni di backup. Gli account di servizio vengono utilizzati per eseguire backup simultanei in modo efficiente. 
---
= Aggiungere ulteriori account di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se necessario, è possibile aggiungere ulteriori account di servizio per migliorare le prestazioni di backup. Gli account di servizio vengono utilizzati per eseguire backup simultanei in modo efficiente.

.Fasi
. Accedere a Microsoft 365 Management Portal utilizzando un account con privilegi di amministratore.
. Fare clic sull'icona di avvio dell'applicazione, quindi fare clic su *Admin*.
. A sinistra, fare clic su *utenti*, quindi su *utenti attivi*.
. Fare clic su *Add a User* (Aggiungi un utente) per creare un nuovo account.
. Compila il modulo seguendo le istruzioni riportate di seguito.
+
** Utilizzare *Lasciami creare la password*.
** Deselezionare l'opzione *Make this user change loro password when first sign in*.
** Selezionare il ruolo *Customized Administrator*.
** Selezionare *Exchange Administrator* e *SharePoint Administrator*.
** Selezionare *Crea utente senza licenza prodotto*.


. Per eseguire i backup di Exchange con gli account di servizio appena creati, assegnare i diritti di rappresentazione di Exchange a questi account di servizio appena creati.link:task_configuring_impersonation.html["Configurazione delle rappresentazioni"]



NOTE: Il backup SaaS assegna automaticamente le autorizzazioni su OneDrive e sui siti SharePoint, in modo che non sia necessario assegnarle.


NOTE: È possibile attivare l'autorizzazione a più fattori (MFA) su questo account.
